### ISSUE TITLE
Cash name not being set according to name_cash

### ISSUE THREAD

**Issue by Member05022018** [sannysc/amnis#1]
Cash remains called "cash" regardless of settings in the sh_schema.

`Clockwork.option:SetKey("name_cash", "Tokens");` appears to have no effect.

Note: I am using the GitHub version of Clockwork and while I am using a modified schema, it is only different from HL2RP in name.

**Comment by sannysc** [comment]
Fixed in CloudSixteen/Clockwork@58c29c584ac49ae687a8643e43622d8f38d39d46
