### ISSUE TITLE
Names and physical descriptions on corpses

### ISSUE THREAD

**Issue by Member05022018** [sannysc/amnis#3]
In the same way that a character's name and physical description appears when alive, the same should be for their corpse. Fix (if it is native behaviour, but broken) or implement this.

In addition, include a "This person is dead" (or something similar) indicator - similar to what would appear if they were unconscious.

Note: I am using the GitHub version of Clockwork and while I am using a modified schema, it is only different from HL2RP in name.

**Comment by sannysc** [comment]
This is already a thing.

![](https://i.imgur.com/hdWQeaJ.png)

The text disappears when the character respawns. Do you want the text to stay?

**Comment by Member05022018** [comment]
Yes, I want it to stay.

**Comment by sannysc** [comment]
![](https://i.imgur.com/xsPnFfy.jpg)
