### ISSUE TITLE
Fix salesman not responding when player attempts to purchase an item they cannot afford

### ISSUE THREAD

**Issue by Member05022018** [sannysc/amnis#5]
When attempting to purchase an item from a salesman, they will have no response and an error will return.

According to: https://github.com/CloudSixteen/Clockwork/issues/389

The error is as follows:
FormatCash - [C]:-1
unknown - gamemodes/clockwork/plugins/salesmen/plugin/sv_plugin.lua:76
func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:127
unknown - lua/includes/extensions/net.lua:32

Note: I am using the GitHub version of Clockwork and while I am using a modified schema, it is only different from HL2RP in name.

**Comment by sannysc** [comment]
Fixed in CloudSixteen/Clockwork@b9d7f0e7306f0fdace7d30c635daec1d29ab122f
