### ISSUE TITLE
Salesman console error spam

### ISSUE THREAD

**Issue by Member05022018** [sannysc/amnis#6]
Encountered a new issue I will pay you to fix.

Main C16 thread:
http://forums.cloudsixteen.com/threads/console-spam-when-choosing-items-for-salesman.35466/

Whenever I enter "Items" when using /salesmanadd, console spams me with this error message:

[Amnis|2|STEAM_0:1:436790851] Lua Error:

[ERROR] gamemodes/clockwork/framework/libraries/sh_item.lua:819: attempt to concatenate field 'weight' (a table value)
1. GetMarkupToolTip - gamemodes/clockwork/framework/libraries/sh_item.lua:819
2. unknown - gamemodes/clockwork/plugins/salesmen/plugin/derma/cl_salesman.lua:485

The spam only stops when moving to a different panel in the salesman menu.

Note: This issue does not appear related to an individual item itself and removing the weight value on an item appears to have no effect.

**Comment by sannysc** [comment]
Weird, I can't read your C16 thread. Says I don't have permission.

I'm not getting this error. It sounds like you may have custom items or plugins that improperly set the weight for 1 or more items. The weight should be a number, but is actually a table.

**Comment by Member05022018** [comment]
I have tried removing all items apart from sh_breens_water, which is as follows:
`--[[
    © CloudSixteen.com do not share, re-distribute or modify
    without permission of its author (kurozael@gmail.com).
--]]

local ITEM = Clockwork.item:New();

ITEM.name = "ItemBreensWater";
ITEM.uniqueID = "breen_s_water";
ITEM.cost = 1;
ITEM.model = "models/props_junk/popcan01a.mdl";
ITEM.weight = 0.5;
ITEM.access = "1";
ITEM.useText = "Drink";
ITEM.business = true;
ITEM.category = "Consumables";
ITEM.description = "ItemBreensWaterDesc";

-- Called when a player uses the item.
function ITEM:OnUse(player, itemEntity)
    player:SetCharacterData("Stamina", 100);
end;

-- Called when a player drops the item.
function ITEM:OnDrop(player, position) end;

-- Called when the item's functions should be edited.
function ITEM:OnEditFunctions(functions)
    if (Schema:PlayerIsCombine(Clockwork.Client, false)) then
        for k, v in pairs(functions) do
            if (v == "Drink") then functions[k] = nil; end;
        end;
    end;
end;

ITEM:Register();`

Would it help to give you FTP access to the server?

**Comment by sannysc** [comment]
FTP access isn't needed. I think I'm using an outdated version of HL2 RP. Can you send me a zip of the latest version on steam?

**Comment by Member05022018** [comment]
Correct me if I'm wrong, but I'm fairly certain it is not permitted to upload and provide a public download for the HL2RP?

**Comment by sannysc** [comment]
Just send it through steam like I said. If you don't want to do that, then consider this issue closed because I can't fix something that isn't broken on my end.

**Comment by sannysc** [comment]
The ToS says you should not distribute your schema to other people.

http://cloudsixteen.com/tos.html

But I'm a C16 developer. If you are scared of breaking the law or ToS or whatever, then I cannot help you on this issue.
